# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: EECS 298
tagline: Mathematics for Machine Learning, Fall 2025 at the University of Michigan
# description: A modern, highly customizable, responsive Jekyll template for course websites
author: EECS 298 course staff
baseurl: '/math-for-ML' # the subpath of your site, e.g. /blog
url: 'https://rampure.org' # the base hostname & protocol for your site, e.g. http://example.com
exclude: ["Gemfile", "Gemfile.lock", "LICENSE"]

# Theme settings
remote_theme: just-the-docs/just-the-docs@v0.9.0
color_scheme: um
search_enabled: true
heading_anchors: true
permalink: pretty
# for sticky scroll
sass:
  custom_css: _sass/custom/custom.scss

# Add custom CSS
aux_links_new_tab: true
css:
  - /assets/css/custom.css

# aux_links:
#   GitHub:
#     - 'https://github.com/practicaldsc/wn25'
#   🧠 Study:
#     - 'https://study.practicaldsc.org/'
#   Ed:
#     - 'https://edstem.org/us/courses/69737/discussion/'
#   Gradescope:
#     - 'https://www.gradescope.com/courses/930446/'
#   🤔 Lecture Questions:
#     - 'https://docs.google.com/forms/d/e/1FAIpQLSd4oliiZYeNh76jWy-arfEtoAkCrVSsobZxPwxifWggo3EO0Q/viewform'
#   📬 Feedback:
#     - 'https://docs.google.com/forms/d/e/1FAIpQLScjlYueonz7_ye6NtyIwdboOuQniPPxcCjsoRfjB4rPKDxKRg/viewform'

footer_content:

# Collections for website data
collections:
  staffers:
  staffersnobio:
  modules:
  schedules:
  announcements:
# Default layouts for each collection type
defaults:
  - scope:
      path: ''
      type: staffers
    values:
      layout: staffer
      height: 300
      width: 300
  - scope:
      path: ''
      type: staffersnobio
    values:
      layout: staffer-no-bio
      height: 300
      width: 300
  - scope:
      path: ''
      type: modules
    values:
      layout: module
  - scope:
      path: ''
      type: schedules
    values:
      layout: schedule
  - scope:
      path: ''
      type: announcements
    values:
      layout: announcement

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

liquid:
  error_mode: strict
  strict_filters: true

# callouts
callouts:
  red:
    title: 
    color: red
  yellow:
    title: 
    color: yellow
  blue:
    title: 
    color: blue
  green:
    title: 
    color: green

plugins:
  - jekyll-redirect-from
